import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../data/models/support_ticket.dart';
import '../providers/support_ticket_provider.dart';
import 'package:botleji/l10n/app_localizations.dart';

class CreateTicketScreen extends ConsumerStatefulWidget {
  final Map<String, dynamic>? preFilledData;

  const CreateTicketScreen({super.key, this.preFilledData});

  @override
  ConsumerState<CreateTicketScreen> createState() => _CreateTicketScreenState();
}

class _CreateTicketScreenState extends ConsumerState<CreateTicketScreen> {
  bool _isLoading = false;
  
  // Auto-generated values
  late String _autoGeneratedTitle;
  late TicketCategory _selectedCategory;
  late String _description;
  final TicketPriority _selectedPriority = TicketPriority.medium; // Always medium

  @override
  void initState() {
    super.initState();
    _initializeTicketData();
  }

  void _initializeTicketData() {
    if (widget.preFilledData != null) {
      final data = widget.preFilledData!;

      // Auto-generate title based on category and context
      _autoGeneratedTitle = _generateTitle(data);

      // Auto-select category from previous step
      if (data['category'] != null) {
        _selectedCategory = _getCategoryFromString(data['category']);
      } else {
        _selectedCategory = TicketCategory.generalSupport;
      }

      // Get description from previous step
      if (data['itemDescription'] != null) {
        _description = data['itemDescription'];
      } else if (data['description'] != null) {
        _description = data['description'];
      } else {
        _description = 'No description provided';
      }
    } else {
      _autoGeneratedTitle = AppLocalizations.of(context).supportRequest;
      _selectedCategory = TicketCategory.generalSupport;
      _description = AppLocalizations.of(context).noDescriptionProvided;
    }
  }

  String _generateTitle(Map<String, dynamic> data) {
    final l10n = AppLocalizations.of(context);
    final category = data['category'] ?? 'general';
    final categoryTitle = data['categoryTitle'] ?? l10n.support;
    final itemTitle = data['itemTitle'];
    
    // Generate title based on category and context
    switch (category) {
      case 'drops':
        if (itemTitle != null && itemTitle.toString().contains('Drop')) {
          return itemTitle.toString();
        }
        return '${l10n.dropIssue} - $categoryTitle';
      case 'applications':
        if (itemTitle != null) {
          return itemTitle.toString();
        }
        return '${l10n.applicationIssue} - $categoryTitle';
      case 'payments':
        return '${l10n.paymentIssue} - $categoryTitle';
      case 'account':
        return '${l10n.accountIssue} - $categoryTitle';
      case 'technical':
        return '${l10n.technicalIssue} - $categoryTitle';
      case 'general':
        if (itemTitle != null) {
          return itemTitle.toString();
        }
        return l10n.generalSupportRequest;
      default:
        if (itemTitle != null) {
          return itemTitle.toString();
        }
        return '$categoryTitle ${l10n.supportRequest}';
    }
  }

  TicketCategory _getCategoryFromString(String categoryString) {
    switch (categoryString) {
      case 'drops':
        return TicketCategory.dropCreation;
      case 'applications':
        return TicketCategory.collectorApplication;
      case 'account':
        return TicketCategory.authentication;
      case 'technical':
        return TicketCategory.appTechnical;
      case 'payments':
        return TicketCategory.paymentRewards;
      case 'general':
        return TicketCategory.generalSupport;
      case 'authentication':
        return TicketCategory.authentication;
      case 'app_technical':
        return TicketCategory.appTechnical;
      case 'drop_creation':
        return TicketCategory.dropCreation;
      case 'collection_navigation':
        return TicketCategory.collectionNavigation;
      case 'collector_application':
        return TicketCategory.collectorApplication;
      case 'payment_rewards':
        return TicketCategory.paymentRewards;
      case 'statistics_history':
        return TicketCategory.statisticsHistory;
      case 'role_switching':
        return TicketCategory.roleSwitching;
      case 'communication':
        return TicketCategory.communication;
      case 'general_support':
        return TicketCategory.generalSupport;
      default:
        return TicketCategory.generalSupport;
    }
  }


  Future<void> _submitTicket() async {
    setState(() => _isLoading = true);

    try {
      await ref.read(supportTicketProvider.notifier).createTicket(
            title: _autoGeneratedTitle,
            description: _description,
            category: _selectedCategory,
            priority: _selectedPriority, // Always medium
            contextMetadata: widget.preFilledData?['metadata'],
            relatedDropId: widget.preFilledData?['metadata']?['dropId'] ?? 
                          widget.preFilledData?['metadata']?['dropoffId'],
            relatedCollectionId:
                widget.preFilledData?['metadata']?['collectionId'],
            relatedApplicationId:
                widget.preFilledData?['metadata']?['applicationId'],
            location: widget.preFilledData?['metadata']?['location'],
          );

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(AppLocalizations.of(context).supportTicketCreatedSuccessfully),
            backgroundColor: const Color(0xFF00695C),
          ),
        );
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(AppLocalizations.of(context).failedToCreateTicket(e.toString())),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey[50],
      appBar: AppBar(
        title: Text(AppLocalizations.of(context).reviewTicket),
        backgroundColor: const Color(0xFF00695C),
        foregroundColor: Colors.white,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            // Header
            Container(
              padding: const EdgeInsets.all(20),
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  colors: [
                    const Color(0xFF00695C).withOpacity(0.1),
                    const Color(0xFF00695C).withOpacity(0.05),
                  ],
                  begin: Alignment.topLeft,
                  end: Alignment.bottomRight,
                ),
                borderRadius: BorderRadius.circular(16),
                border: Border.all(
                  color: const Color(0xFF00695C).withOpacity(0.2),
                  width: 1,
                ),
              ),
              child: Row(
                children: [
                  Container(
                    padding: const EdgeInsets.all(12),
                    decoration: BoxDecoration(
                      color: const Color(0xFF00695C).withOpacity(0.1),
                      borderRadius: BorderRadius.circular(12),
                    ),
                    child: const Icon(
                      Icons.receipt_long,
                      color: Color(0xFF00695C),
                      size: 24,
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          AppLocalizations.of(context).reviewYourTicket,
                          style: const TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.bold,
                            color: Color(0xFF00695C),
                          ),
                        ),
                        const SizedBox(height: 4),
                        Text(
                          AppLocalizations.of(context).pleaseReviewDetailsBeforeCreating,
                          style: TextStyle(
                            fontSize: 14,
                            color: Colors.grey[600],
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 24),

            // Title Summary Card
            _buildSummaryCard(
              icon: Icons.title,
              label: AppLocalizations.of(context).title,
              value: _autoGeneratedTitle,
              iconColor: Colors.blue,
            ),
            const SizedBox(height: 12),

            // Category Summary Card
            _buildSummaryCard(
              icon: Icons.category,
              label: AppLocalizations.of(context).category,
              value: _getCategoryDisplayName(_selectedCategory),
              iconColor: Colors.green,
            ),
            const SizedBox(height: 12),

            // Priority Summary Card
            _buildSummaryCard(
              icon: _getPriorityIcon(_selectedPriority),
              label: AppLocalizations.of(context).priority,
              value: _getPriorityDisplayName(_selectedPriority),
              iconColor: _getPriorityColor(_selectedPriority),
            ),
            const SizedBox(height: 12),

            // Description Summary Card
            _buildSummaryCard(
              icon: Icons.description,
              label: AppLocalizations.of(context).description,
              value: _description,
              iconColor: Colors.orange,
              isMultiline: true,
            ),
            const SizedBox(height: 24),

            // Confirm & Create Button
            ElevatedButton(
              onPressed: _isLoading ? null : _submitTicket,
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFF00695C),
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(vertical: 16),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
                elevation: 2,
              ),
              child: _isLoading
                  ? const SizedBox(
                      height: 20,
                      width: 20,
                      child: CircularProgressIndicator(
                        strokeWidth: 2,
                        valueColor:
                            AlwaysStoppedAnimation<Color>(Colors.white),
                      ),
                    )
                  : Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        const Icon(Icons.check_circle, size: 20),
                        const SizedBox(width: 8),
                        Text(
                          AppLocalizations.of(context).confirmAndCreateTicket,
                          style: const TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                      ],
                    ),
            ),
            const SizedBox(height: 16),

            // Cancel Button
            TextButton(
              onPressed: _isLoading ? null : () => Navigator.pop(context),
              child: Text(
                AppLocalizations.of(context).cancel,
                style: const TextStyle(
                  fontSize: 14,
                  color: Colors.grey,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildSummaryCard({
    required IconData icon,
    required String label,
    required String value,
    required Color iconColor,
    bool isMultiline = false,
  }) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.grey[200]!),
        boxShadow: [
          BoxShadow(
            color: Colors.grey.withOpacity(0.05),
            blurRadius: 4,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Row(
        crossAxisAlignment: isMultiline ? CrossAxisAlignment.start : CrossAxisAlignment.center,
        children: [
          Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: iconColor.withOpacity(0.1),
              borderRadius: BorderRadius.circular(8),
            ),
            child: Icon(
              icon,
              color: iconColor,
              size: 20,
            ),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  label,
                  style: TextStyle(
                    fontSize: 12,
                    fontWeight: FontWeight.w600,
                    color: Colors.grey[600],
                    letterSpacing: 0.5,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  value,
                  style: TextStyle(
                    fontSize: 14,
                    fontWeight: FontWeight.w500,
                    color: Colors.grey[900],
                    height: isMultiline ? 1.4 : 1.2,
                  ),
                  maxLines: isMultiline ? null : 2,
                  overflow: isMultiline ? TextOverflow.visible : TextOverflow.ellipsis,
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  String _getCategoryDisplayName(TicketCategory category) {
    final l10n = AppLocalizations.of(context);
    switch (category) {
      case TicketCategory.authentication:
        return l10n.authenticationAccount;
      case TicketCategory.appTechnical:
        return l10n.appTechnicalIssues;
      case TicketCategory.dropCreation:
        return l10n.dropCreationManagement;
      case TicketCategory.collectionNavigation:
        return l10n.collectionNavigation;
      case TicketCategory.collectorApplication:
        return l10n.collectorApplicationCategory;
      case TicketCategory.paymentRewards:
        return l10n.paymentRewards;
      case TicketCategory.statisticsHistory:
        return l10n.statisticsHistory;
      case TicketCategory.roleSwitching:
        return l10n.roleSwitching;
      case TicketCategory.communication:
        return l10n.communication;
      case TicketCategory.generalSupport:
        return l10n.generalSupportCategory;
    }
  }

  String _getPriorityDisplayName(TicketPriority priority) {
    final l10n = AppLocalizations.of(context);
    switch (priority) {
      case TicketPriority.low:
        return l10n.lowPriority;
      case TicketPriority.medium:
        return l10n.mediumPriority;
      case TicketPriority.high:
        return l10n.highPriority;
      case TicketPriority.urgent:
        return l10n.urgent;
    }
  }

  IconData _getPriorityIcon(TicketPriority priority) {
    switch (priority) {
      case TicketPriority.low:
        return Icons.keyboard_arrow_down;
      case TicketPriority.medium:
        return Icons.remove;
      case TicketPriority.high:
        return Icons.keyboard_arrow_up;
      case TicketPriority.urgent:
        return Icons.priority_high;
    }
  }

  Color _getPriorityColor(TicketPriority priority) {
    switch (priority) {
      case TicketPriority.low:
        return Colors.green;
      case TicketPriority.medium:
        return Colors.orange;
      case TicketPriority.high:
        return Colors.red;
      case TicketPriority.urgent:
        return Colors.purple;
    }
  }
}
