// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKl55E3W0XDpWXVTN_bGM1mjZT1PLw0tU',
    appId: '1:414913880297:web:42914108ee5ab33f8a9078',
    messagingSenderId: '414913880297',
    projectId: 'botleji',
    authDomain: 'botleji.firebaseapp.com',
    storageBucket: 'botleji.firebasestorage.app',
    measurementId: 'G-MYXVY20GC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7OtTkNnKEGECK0kKnNBjeebYFW4w6J2U',
    appId: '1:414913880297:android:d6d7c3324a57c7bb8a9078',
    messagingSenderId: '414913880297',
    projectId: 'botleji',
    storageBucket: 'botleji.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsOtvOkiYqf8tVmtzdbOyihQQ6uf9kdds',
    appId: '1:414913880297:ios:4621c0674928dcfb8a9078',
    messagingSenderId: '414913880297',
    projectId: 'botleji',
    storageBucket: 'botleji.firebasestorage.app',
    iosBundleId: 'com.example.botleji',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsOtvOkiYqf8tVmtzdbOyihQQ6uf9kdds',
    appId: '1:414913880297:ios:4621c0674928dcfb8a9078',
    messagingSenderId: '414913880297',
    projectId: 'botleji',
    storageBucket: 'botleji.firebasestorage.app',
    iosBundleId: 'com.example.botleji',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKl55E3W0XDpWXVTN_bGM1mjZT1PLw0tU',
    appId: '1:414913880297:web:c3c3729f8f4f4e668a9078',
    messagingSenderId: '414913880297',
    projectId: 'botleji',
    authDomain: 'botleji.firebaseapp.com',
    storageBucket: 'botleji.firebasestorage.app',
    measurementId: 'G-Y1VW4DR0P9',
  );
}
